### PR TITLE
add tflite converter

### PR DESCRIPTION
**Pull request by jkamelin**

### CODE REVIEW

**Review by ilya-naumov — APPROVED** [review]

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
@jkamelin please rebase to current develop (there is fix for red precommit https://github.com/YADRO-KNS/dl-benchmark/actions/runs/3927947004)

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Review by zmaslova — APPROVED** [review]

**Comment by zmaslova** [comment]
@jkamelin thanks! you can merge it now 😄

**Pull request merged**
